### ISSUE TITLE
Open Link doesn't work

### ISSUE THREAD

**Issue by mnatalia** [mxmo-co/title_links#4] opened 2017-02-07 21:55 UTC
Hi, great application. Thanks. I have two questions:
1. In table view I saw Item Code and when I open table's row I saw Item Name
![screenshot from 2017-02-07 23 48 47](https://cloud.githubusercontent.com/assets/9428212/22713237/4794becc-ed90-11e6-8e08-4834c234e4bc.png)
![screenshot from 2017-02-07 23 48 54](https://cloud.githubusercontent.com/assets/9428212/22713241/49533414-ed90-11e6-9a7b-99dbe7b53f43.png)

2. When I push "Open Link" near Item code I receive error
![screenshot from 2017-02-07 23 49 00](https://cloud.githubusercontent.com/assets/9428212/22713256/626b6188-ed90-11e6-941b-829e67d53d72.png)

Btw, I tested it on 
ERPNext: v7.2.18
Frappe Framework: v7.2.14
Title Links: v0.0.1

sorry if I shouldn't have tested it on these versions

**Comment by MaxMorais** [comment] 2017-02-07 22:33
@mnatalia Thanks to report, Ill publish a patch!

To remove the app, run "bench remove-from-installed-apps title_links", while I'm fixing this!

**Comment by mnatalia** [comment] 2017-02-07 22:37
@MaxMorais Thanks.

**Comment by MaxMorais** [comment] 2017-02-08 00:33
@mnatalia it's fixed

**Comment by MaxMorais** [comment] 2017-02-08 00:59
@mnatalia I forgot the fix for the table grid!

I'll investigate it tomorrow!

**Comment by joezsweet** [comment] 2017-02-08 08:09
Hi Max, i'm getting an error:

Uncaught TypeError: Cannot read property 'doctype' of undefined
    at Class.make_column (http://is.dev:8000/assets/title_links/js/title_links.js:243:20)
    at Class.prototype.(anonymous function) [as make_column] (http://is.dev:8000/assets/js/desk.min.js:91:20)
    at Class.setup_columns (http://is.dev:8000/assets/js/form.min.js:3605:23)
    at Class.render_row (http://is.dev:8000/assets/js/form.min.js:3553:8)
    at Class.make (http://is.dev:8000/assets/js/form.min.js:3439:9)
    at Class.init (http://is.dev:8000/assets/js/form.min.js:3412:8)
    at new Class (http://is.dev:8000/assets/js/desk.min.js:105:15)
    at Class.make_head (http://is.dev:8000/assets/js/form.min.js:2907:22)
    at Class.refresh (http://is.dev:8000/assets/js/form.min.js:2944:9)
    at HTMLDivElement.<anonymous> (http://is.dev:8000/assets/js/desk.min.js:5548:12)

Can you please have a  look?

**Comment by joezsweet** [comment] 2017-02-08 08:14
@MaxMorais got the error, on frappe.call args should be: 

```
			'args': {
				doctype: me.frm.doc.doctype,
				name: me.frm.doc.name
			},

```

**Comment by MaxMorais** [comment] 2017-02-08 10:52
@joezsweet, thanks for the clarification, but has another bug, it's referencing the name of the row, not the linked record!

I published a patch now!, It should be fixed!

**Comment by joezsweet** [comment] 2017-02-08 11:02
Great! 

Another small thing; it seems title_name field is not shown as search field even if its listed, it is by design? Should be added?

**Comment by MaxMorais** [comment] 2017-02-08 11:09
@joezsweet yes it's by design because in place of search_field is displayed name field, while title_field is used to display, but you can search by the content of the title_field, as related here 

https://github.com/mxmo-co/title_links/blob/master/title_links/routes.py#L88

**Comment by joezsweet** [comment] 2017-02-08 11:15
I see, my point is that searching be title_field would not let the user know if it's the correct one by not displaying it ..not sure if u get the point ..

let's try with an example: 

<img width="522" alt="schermata 2017-02-08 alle 10 18 45" src="https://cloud.githubusercontent.com/assets/11652845/22734984/017f4a16-edf8-11e6-8d5f-0e61344e2f8d.png">

If you search, lets say, for PESCHERIA, and it's not displayed in the search field, how do i know that C-011, 049 is exately PESCHERIA?

**Comment by MaxMorais** [comment] 2017-02-08 11:17
@joezsweet it's displayed instead of "C-011" you will get "PESCHERIA", that is the purpose of this hack, it will replace the `name` display to `title`

**Comment by joezsweet** [comment] 2017-02-08 11:21
@MaxMorais  I'm not explayin correctly ..i'd like to have all defined search fields in the drop down window ..including the one used for title_field so that i'll be aware of what I'm choosing

**Comment by MaxMorais** [comment] 2017-02-08 11:26
@joezsweet, do you have! the unique included field in search is `name` https://github.com/mxmo-co/title_links/blob/master/title_links/routes.py#L70

**Comment by joezsweet** [comment] 2017-02-08 11:27
wait ...let me pull last version and i'll post screenshot

**Comment by MaxMorais** [comment] 2017-02-08 11:30
@mnatalia, @joezsweet issues regarding JS and GridRow fixed!

I'm closing this issue again!

@joezsweet, if you need fell free to open another issue!

**Comment by joezsweet** [comment] 2017-02-08 11:31
Ok

**Closed by MaxMorais** 2017-02-08 11:30 UTC
Labels: bug, enhancement

**Comment by mnatalia** [comment] 2017-02-08 14:39
@MaxMorais thanks;-)
